apiVersion: apps/v1
kind: Deployment
metadata:
  name: designo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: designo-app
  template:
    metadata:
      labels:
        app: designo-app
    spec:
      containers:
        - name: designo
          image: temple4b/designo
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
