apiVersion: apps/v1
kind: Deployment
metadata:
  name: designo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: designo-app
  template:
    metadata:
      labels:
        app: designo-app
    spec:
      containers:
        - name: designo
          image: temple4b/designo
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: node-port
spec:
  type: NodePort
  selector:
    app: designo-app
  ports:
    - port: 3050
      targetPort: 3000
      nodePort: 31515
